railstest/config/routes.rb
Rails.application.routes.draw do
 
  resources :articles
 
  root 'welcome#index'
end

railstest/app/models/article.rb
class Article < ActiveRecord::Base
end

railstest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

railstest/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
  end

  def create
    @article = Article.new(article_params)
 
    @article.save
    redirect_to @article
  end
  
  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
    
  def show
    @article = params[:id]
    @check=1
  end
    
  
end

railstest/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

railstest/app/helpers/application_helper.rb
module ApplicationHelper
end

railstest/app/helpers/articles_helper.rb
module ArticlesHelper
end

railstest/app/helpers/welcome_helper.rb
module WelcomeHelper
end

railstest/app/views/articles/new.html.erb
<h1>new article </h1>
<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

railstest/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article %>
  <%= @check %>
</p>
 

railstest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railstest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

railstest/app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>